export default function AboutPage (){
return(
    <section className="flex h-screen justify-center items-center">
        <div className='container bg-slate-900 p-3'>
            <h3 className='font-bold text-2xl mb-2'>About Us</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae qui quisquam harum ipsam, facilis temporibus quibusdam beatae ipsum maxime ratione quas sed et architecto facere, rem iure praesentium magnam hic dignissimos deserunt aut totam commodi doloribus eum? Quibusdam, aliquam doloribus quis odio eius similique vel, laborum ea dignissimos expedita ad blanditiis sunt sit eligendi ut rem accusantium illum possimus ducimus vero consectetur! Est dolorum omnis quisquam ad laborum mollitia amet, hic deserunt dolores dicta sint similique quod adipisci, quaerat exercitationem eaque sapiente fugit iusto assumenda explicabo tempore magni facere. Et dolore dolor impedit asperiores animi quae possimus fugiat dicta at sed ipsam quidem quaerat eos aliquid porro illum, pariatur delectus corrupti qui. Similique distinctio officia magni, animi ad placeat laboriosam.</p>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. A, cupiditate? Esse perspiciatis est quod, numquam perferendis dignissimos assumenda iusto, totam provident quos neque magnam impedit cumque illum obcaecati voluptas! Pariatur consequuntur animi sunt dolore perferendis iste! Rem, qui facere autem voluptatibus quaerat sunt ipsa molestias beatae harum doloremque similique temporibus aut doloribus veritatis ipsam iure illo accusantium maiores nulla exercitationem laborum. Magnam accusamus deserunt in natus enim alias ex dicta nemo, repellat iusto nostrum nisi. Repellat deleniti iure impedit inventore quaerat accusantium expedita ducimus, dicta assumenda libero omnis quod nihil eveniet similique recusandae, quisquam aut vitae. Tempora quis aspernatur placeat doloribus in laboriosam, aliquid ullam voluptatibus qui incidunt eligendi enim voluptatum excepturi amet quas sed voluptatem culpa! Nam tenetur error odio repellendus praesentium! Aut nesciunt exercitationem pariatur ipsam ad hic nulla omnis molestias. Libero ipsam saepe odio quibusdam. Minus sequi provident explicabo vitae quis tenetur ducimus, sint magni eius maiores magnam, numquam suscipit nostrum minima aliquid consequatur animi quasi ut exercitationem accusamus, odio veniam. Eaque temporibus aliquid dolores rerum, quod hic dignissimos molestias quos praesentium molestiae neque cupiditate esse nam illo accusantium ratione optio, vitae magnam iure facere odio inventore? At accusamus odio consequuntur recusandae neque repellendus dignissimos tenetur totam porro nam expedita doloribus pariatur, perferendis consequatur illum, quisquam sint eum facere voluptate, dolorem minus doloremque voluptatem veritatis nulla. Quas fugit animi inventore, voluptatibus mollitia quam accusantium enim error quo debitis natus iure maxime soluta quidem vitae voluptatum autem a maiores nam nulla nemo excepturi. Tempore ipsa modi reprehenderit enim tenetur perferendis laborum ea corrupti voluptatum!</p>
        </div>
    </section>
)}